#!/bin/sh

set -e

# See if a specific PgSQL database exists.  Returns 0 if it exists,
# and 1 otherwise.
#
# Usage:
#
#    $0 <dbname>
#

RESCOUNT="$(psql -Aqt -c "SELECT COUNT(datname) FROM pg_catalog.pg_database WHERE datname='$1'" template1 2>/dev/null)"

if [ "$RESCOUNT" = "0" ]; then
	exit 1
else
	exit 0
fi
