#!/bin/sh

set -e

# See if a specific PgSQL user is a member of all the listed groups.  A group
# name can be preceded by a '-', in which case the specified group must *not*
# be in the set of groups the user is in.
#
# Returns 0 if everything is OK, 1 otherwise.
#
# Usage:
#
#    $0 <username> <group> [group ...]
#

user="$1"
shift

while [ -n "$1" ]; do
	group="$1"
	shift

	if [ "$(echo "$group" | cut -c 1)" = "-" ]; then
		present="n"
		group="$(echo "$group" | cut -c 2-)"
	else
		present="y"
	fi

	rescount="$(psql -Aqt -c "select COUNT(m.*) FROM pg_catalog.pg_auth_members m JOIN pg_catalog.pg_roles u ON m.member=u.oid JOIN pg_catalog.pg_roles r ON m.roleid=r.oid WHERE u.rolname='$user' AND r.rolname='$group'" template1 2>/dev/null)"

	if [ "$rescount" = "0" -a "$present" = "y" ] || [ "$rescount" != "0" -a "$present" = "n" ]; then
		exit 1
	fi
done

# The groups are exactly as we want them, so we're golden
exit 0
