#!/bin/sh

set -e

# Ensure that the specified user is a member of all the specified groups.
#
# Usage:
#
#    $0 <username> <group> [group ...]
#

user="$1"
shift

while [ -n "$1" ]; do
	group="$1"
	shift

	if [ "$(echo "$group" | cut -c 1)" = "-" ]; then
		psql -Aqt -c "REVOKE \"$group\" FROM \"$user\"" template1 2>/dev/null
	else
		psql -Aqt -c "GRANT \"$group\" TO \"$user\"" template1 2>/dev/null
	fi
done

